In [2]:
#library
import cv2 #tüm görüntü işleme işlemleri pip install opencv-python
import numpy as np #matris işlemleri pip install numpy

In [2]:
#reading, saving, displaying images
img=cv2.imread("datasets/yoda.jpg")

cv2.imwrite("datasets/yoda_copy.jpg", img) #istediğmiz dizine görüntüyü kopyalama

cv2.imshow("yoda", img) #ekranda resmi gösterir

cv2.waitKey(0) #ekranda bekleme süresi

cv2.destroyAllWindows() #tüm pencereleri kapatır

In [3]:
#scaling
img=cv2.imread("datasets/yoda.jpg")
resized_img = cv2.resize(img, (128,128))

print("original image:" , img)
print("resized image: " , resized_img)

cv2.imshow("original image", img)
cv2.imshow("resized image", resized_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

original image: [[[11 11 11]
  [11 11 11]
  [11 11 11]
  ...
  [25 25 25]
  [25 25 25]
  [25 25 25]]

 [[11 11 11]
  [11 11 11]
  [11 11 11]
  ...
  [25 25 25]
  [25 25 25]
  [25 25 25]]

 [[11 11 11]
  [11 11 11]
  [11 11 11]
  ...
  [25 25 25]
  [25 25 25]
  [25 25 25]]

 ...

 [[37 21  4]
  [37 21  4]
  [37 21  4]
  ...
  [46 42 31]
  [46 42 31]
  [46 42 31]]

 [[37 21  4]
  [37 21  4]
  [37 21  4]
  ...
  [46 42 31]
  [46 42 31]
  [46 42 31]]

 [[37 21  4]
  [37 21  4]
  [37 21  4]
  ...
  [46 42 31]
  [46 42 31]
  [46 42 31]]]
resized image:  [[[12 12 12]
  [14 14 14]
  [15 15 15]
  ...
  [16 16 16]
  [25 25 25]
  [25 25 25]]

 [[12 12 12]
  [13 13 13]
  [15 15 15]
  ...
  [23 23 23]
  [24 24 24]
  [26 26 26]]

 [[12 12 12]
  [13 13 13]
  [15 15 15]
  ...
  [23 23 23]
  [24 24 24]
  [25 25 25]]

 ...

 [[46 39 32]
  [49 41 34]
  [53 41 35]
  ...
  [43 32 23]
  [41 29 20]
  [45 33 20]]

 [[40 27 11]
  [41 26  8]
  [39 25  6]
  ...
  [40 33 24]
  [38 31 22]
  [44 38 25]]

 [[37 21  

In [4]:
#roi(region of image)

img= cv2.imread("datasets/yoda.jpg")
face= img[90:400, 110:615] #ilk girilen pikseller dikey, ikinci girilen pikseller yatay

cv2.imshow("yoda", img)
cv2.imshow("face image", face)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [5]:
#colorspace
img = cv2.imread("datasets/yoda.jpg")#cv2 metodu görüntüleri her zaman BGR formatında okur
print("original image",img.shape)

gray =cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #görüntünün colorSpace değiştirme
print("Grayscale image", gray.shape) #.shape ile kanal sayısını derinliğini öğreniriz

hsv= cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print("HSV image", hsv.shape)

rgb=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print("RGB image", rgb.shape)

cv2.imshow("original image", img)
cv2.imshow("grayscale image", gray)
cv2.imshow("HSV image", hsv)
cv2.imshow("RGB image", rgb)

cv2.waitKey(0)
cv2.destroyAllWindows()

original image (1024, 768, 3)
Grayscale image (1024, 768)
HSV image (1024, 768, 3)
RGB image (1024, 768, 3)


In [6]:
#drawing functions - circle

color = (255,255,0)
canva =np.zeros((512,512,3), dtype=np.uint8)+100
print("canva image: ", canva.shape)

cv2.circle(canva, (100,100), 50, color,-1) 
cv2.circle(canva, (250,250), 50, color, 2)
#0 yazarsak dış kenar en ince çizgi ile çizilir
#-1 yazarsak içini doldurur.

cv2.imshow("canva", canva)
cv2.waitKey(0)
cv2.destroyAllWindows()

canva image:  (512, 512, 3)


In [21]:
#drawing rectangle
color = (255,255,0)
canva=np.zeros((512,512,3), dtype=np.uint8)+100
print("canva images:", canva.shape)

cv2.rectangle(canva, (100,100), (200,150), color, 0)
#(giriş görüntüsü, dikdörtgenin koordinatları, rengi, kalınlığı)
cv2.rectangle(canva, (50,50), (100,400), color, -1)

cv2.imshow("canva", canva)
cv2.waitKey(0)
cv2.destroyAllWindows()


canva images: (512, 512, 3)


In [25]:
#drawing function - text
#opencv'de bazı yazı fontları bulunmaktadır 
"""
HERSHEY_SIMPLEX
HERSHEY_PLAIN
HERSHEY_DUPLEX
HERSHEY_COMPLEX
HERSHEP_TRIPLEX
HERSHEY_COMPLEX_SMALL
HERSHEY_SCRIPT_SIMPLEX
HERSHEY_SCRIPT_COMPLEX
"""

color=(255,255,0)
font= cv2.FONT_HERSHEY_SIMPLEX
font_scale=5
thickness=2
line_type=cv2.LINE_AA

canva =np.zeros((512,512,3), dtype=np.uint8)+255
#(0,0,0) --> (255,255,255)
print("canva", canva.shape)

cv2.putText(canva, "Introduction of OpenCV", (100,100), font, font_scale, color, thickness, line_type)

cv2.imshow("canva", canva)
cv2.waitKey(0)
cv2.destroyAllWindows()

canva (512, 512, 3)


In [9]:
#video displaying
import cv2

capture=cv2.VideoCapture("datasets/skate.mp4")  # webcam kullanılacaksa cv2.VideoCapture(0) 
#opencv kare kare okur, çıktı verir bu yüzden video okumak için bir döngüye ihtiyaç vardır
while True:
    ret, frame= capture.read()  #return edilen değer(true ya da false) , frame
    if ret==False:
        break

    resized_frame=cv2.resize(frame, (450, 200))
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    cv2.imshow("Original Video", frame)
    cv2.imshow("HSV Video", hsv)
    cv2.imshow("resized video", resized_frame)

    if cv2.waitKey(45)& 0xFF == ord("q"): 
        break
    #waitKey(videodaki bir karenin ekranda ne kadar uzun kaldığı sayı arttıkça video yavaşlar) & q tuşunun klavyedeki hex kodu.

capture.release() #video ile yapılan işlem bitti, videoyu serbest bırak
cv2.destroyAllWindows()

